In [ ]:
## Stock price prediction using BERT and GAN, 2017

In [8]:
import yfinance as yf
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error 
from sklearn.metrics import mean_absolute_error
import tensorflow as tf
from tensorflow.keras.layers import Dense, LSTM, Dropout
from tensorflow.keras.models import Sequential
from keras import optimizers
from keras import backend as K

import random
import train_test as tt
import os

In [9]:
def MAPE(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100 

def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true)))

In [10]:
def seed_everything(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    tf.random.set_seed(seed)

seed_everything(42)

In [4]:
################################### 논문 재현(변수 다르고, APPLE 사용) #######################

In [11]:
dir = "/home/whfhrs3260/csv_data/price_data_score_10years.csv"
stock = "AAPL"
variable = ["before_close","Score"]
window_size = 3
start_date = "2010-07-01"
end_date = "2020-07-31"

scaler_x, scaler_y,x, y, x_t, y_t = tt.train_test_result(dir, stock, variable, window_size, start_date, end_date)

lstm_1_model = Sequential()
lstm_1_model.add(LSTM(128, input_shape = (x.shape[1],x.shape[2])))
lstm_1_model.add(Dense(64))
lstm_1_model.add(Dense(1,activation="tanh"))
adam = optimizers.Adam(learning_rate=0.0012)
lstm_1_model.compile(optimizer=adam, loss = "mse")
history = lstm_1_model.fit(x, y, epochs=150, batch_size=64, validation_split=0.2)
    
lstm_1_pred = lstm_1_model.evaluate(x_t, y_t)

[*********************100%***********************]  1 of 1 completed


/home/whfhrs3260/Python/10year_data/review/train_test.py:69: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  set_news_data_date.price_date[i]=standard  + datetime.timedelta(days=1)


[*********************100%***********************]  1 of 1 completed


/home/whfhrs3260/Python/10year_data/review/train_test.py:110: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price_data.before_close[i+1] = price_data.Close[i]


Epoch 1/150
23/23 [==============================] - 2s 23ms/step - loss: 0.0044 - val_loss: 0.0011
Epoch 2/150
23/23 [==============================] - 0s 9ms/step - loss: 5.2130e-04 - val_loss: 1.6892e-04
Epoch 3/150
23/23 [==============================] - 0s 10ms/step - loss: 7.8312e-05 - val_loss: 2.8532e-05
Epoch 4/150
23/23 [==============================] - 0s 10ms/step - loss: 2.5005e-05 - val_loss: 2.5149e-05
Epoch 5/150
23/23 [==============================] - 0s 10ms/step - loss: 1.9687e-05 - val_loss: 3.2435e-05
Epoch 6/150
23/23 [==============================] - 0s 10ms/step - loss: 1.9943e-05 - val_loss: 3.5820e-05
Epoch 7/150
23/23 [==============================] - 0s 10ms/step - loss: 1.9957e-05 - val_loss: 2.7917e-05
Epoch 8/150
23/23 [==============================] - 0s 10ms/step - loss: 1.9794e-05 - val_loss: 3.7090e-05
Epoch 9/150
23/23 [==============================] - 0s 10ms/step - loss: 2.0728e-05 - val_loss: 2.6214e-05
Epoch 10/150
23/23 [=================

In [12]:
lstm_1_pred = lstm_1_model.predict(x_t)
lstm_1_pred = scaler_y.inverse_transform(lstm_1_pred)
y_t = scaler_y.inverse_transform(y_t)
root_mean_squared_error(y_t, lstm_1_pred), mean_squared_error(y_t, lstm_1_pred), mean_absolute_error(y_t, lstm_1_pred), MAPE(y_t, lstm_1_pred)

24/24 [==============================] - 0s 2ms/step


(<tf.Tensor: shape=(), dtype=float64, numpy=4.888956048629097>,
 23.90189124542703,
 3.323381629743074,
 5.212607150938138)

In [ ]:
#################################### 2 variable(news, close 사용) #####################################

In [13]:
dir = "/home/whfhrs3260/csv_data/price_data_score_10years.csv"
stock = "^DJI"
variable = ["before_close","Score"]
window_size = 3
start_date = "2012-01-01"
end_date = "2022-04-30"

scaler_x, scaler_y,x, y, x_t, y_t = tt.train_test_result(dir, stock, variable, window_size, start_date, end_date)

lstm_1_model = Sequential()
lstm_1_model.add(LSTM(128, input_shape = (x.shape[1],x.shape[2])))
lstm_1_model.add(Dense(64))
lstm_1_model.add(Dense(1,activation="tanh"))
adam = optimizers.Adam(learning_rate=0.0012)
lstm_1_model.compile(optimizer=adam, loss = "mse")
history = lstm_1_model.fit(x, y, epochs=150, batch_size=64, validation_split=0.2)
    
lstm_1_pred = lstm_1_model.evaluate(x_t, y_t)

[*********************100%***********************]  1 of 1 completed


/home/whfhrs3260/Python/10year_data/review/train_test.py:69: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  set_news_data_date.price_date[i]=standard  + datetime.timedelta(days=1)


[*********************100%***********************]  1 of 1 completed


/home/whfhrs3260/Python/10year_data/review/train_test.py:110: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price_data.before_close[i+1] = price_data.Close[i]


Epoch 1/150
23/23 [==============================] - 2s 24ms/step - loss: 0.0109 - val_loss: 0.0092
Epoch 2/150
23/23 [==============================] - 0s 9ms/step - loss: 7.0805e-04 - val_loss: 9.7312e-04
Epoch 3/150
23/23 [==============================] - 0s 11ms/step - loss: 1.6618e-04 - val_loss: 0.0020
Epoch 4/150
23/23 [==============================] - 0s 11ms/step - loss: 9.6280e-05 - val_loss: 9.4153e-04
Epoch 5/150
23/23 [==============================] - 0s 10ms/step - loss: 6.5872e-05 - val_loss: 9.4320e-04
Epoch 6/150
23/23 [==============================] - 0s 11ms/step - loss: 5.2593e-05 - val_loss: 7.4243e-04
Epoch 7/150
23/23 [==============================] - 0s 10ms/step - loss: 4.6712e-05 - val_loss: 6.0975e-04
Epoch 8/150
23/23 [==============================] - 0s 10ms/step - loss: 4.4098e-05 - val_loss: 5.8363e-04
Epoch 9/150
23/23 [==============================] - 0s 10ms/step - loss: 4.4005e-05 - val_loss: 6.3410e-04
Epoch 10/150
23/23 [=====================

In [14]:
lstm_1_pred = lstm_1_model.predict(x_t)
lstm_1_pred = scaler_y.inverse_transform(lstm_1_pred)
y_t = scaler_y.inverse_transform(y_t)
root_mean_squared_error(y_t, lstm_1_pred), mean_squared_error(y_t, lstm_1_pred), mean_absolute_error(y_t, lstm_1_pred), MAPE(y_t, lstm_1_pred)

25/25 [==============================] - 0s 3ms/step


(<tf.Tensor: shape=(), dtype=float64, numpy=1978.6404844792078>,
 3915018.1668201145,
 1573.587303181234,
 4.856514488232598)

In [15]:
dir_model = "/home/whfhrs3260/model/"
#lstm_1_model.save(dir_model + 'lstm_128_64_window30_10years.h5')

In [ ]:
# model load

In [9]:
from keras.models import load_model

In [16]:
dir = "/home/whfhrs3260/csv_data/price_data_score_10years.csv"
stock = "^DJI"
variable = ["before_close","Score"]
window_size = 30
start_date = "2012-01-01"
end_date = "2022-04-30"

scaler_x, scaler_y,x, y, x_t, y_t = tt.train_test_result(dir, stock, variable, window_size, start_date, end_date)
lstm_1_model = load_model(dir_model + 'lstm_128_64_window30_10years.h5', custom_objects ={"root_mean_squared_error" : root_mean_squared_error})
lstm_1_pred = lstm_1_model.predict(x_t)
lstm_1_model.evaluate(x_t,y_t)

[*********************100%***********************]  1 of 1 completed


/home/whfhrs3260/Python/10year_data/review/train_test.py:63: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  set_news_data_date.price_date[i]=standard  + datetime.timedelta(days=1)


[*********************100%***********************]  1 of 1 completed


/home/whfhrs3260/Python/10year_data/review/train_test.py:100: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price_data.before_close[i+1] = price_data.Close[i]


24/24 [==============================] - 1s 17ms/step - loss: 0.0633 - mse: 0.0059 - mae: 0.0615


[0.06333596259355545, 0.005902477074414492, 0.061517614871263504]

In [17]:
lstm_1_pred = scaler_y.inverse_transform(lstm_1_pred)
y_t = scaler_y.inverse_transform(y_t)
root_mean_squared_error(y_t, lstm_1_pred), mean_squared_error(y_t, lstm_1_pred), mean_absolute_error(y_t, lstm_1_pred), MAPE(y_t, lstm_1_pred)

(<tf.Tensor: shape=(), dtype=float64, numpy=1897.5016574779052>,
 3600512.5401313975,
 1519.3734083721704,
 4.684872964432992)